.PHONY: all compile cl ct fl ft

all: cl ct fl ft

compile:
	javac data_structures/*.java data_structures/implementation/*.java

cl:	compile
	java -ea data_structures/Main cl 4

ct:	compile
	java -ea data_structures/Main ct 4

fl:	compile
	java -ea data_structures/Main fl 4

ft:	compile
	java -ea data_structures/Main ft 4

lfl:	compile
	java -ea data_structures/Main lfl 4

lft:	compile
	java -ea data_structures/Main lft 4
